[package]
name = "bluez"
version = "0.0.2"
authors = ["Ibiyemi Abiodun <ibiyemi@intulon.com>"]
edition = "2018"
description = "Control Bluetooth on Linux."
license = "CC-BY-NC-SA-4.0"

[dependencies]
libc = "0.2.54"
thiserror = "1.0.1"
errno = "0.2.4"
num-traits = "0.2.6"
num-derive = "0.2.5"
bitflags = "1.2.0"
bitvec = "0.16.1"
bytes = "0.4.12"
futures-preview = "0.3.0-alpha.18"
async-std = "0.99.8"
mio = "0.6.19"

[dependencies.thin_main_loop]
version = "0.2.0"

[[bin]]
name = "bin"
path = "src/main.rs"
doc = false