[package]
name = "bluez"
version = "0.0.3"
authors = ["Ibiyemi Abiodun <ibiyemi@intulon.com>"]
edition = "2018"
description = "Control Bluetooth on Linux."
license = "MIT"

[dependencies]
libc = "0.2"
thiserror = "1.0"
num-traits = "0.2"
num-derive = "0.3"
enumflags2 = "0.6"
bytes = "0.5"
bitvec = "0.16"
futures = "0.3.1"
async-std = "1.4"

[[bin]]
name = "bin"
path = "src/main.rs"
doc = false