[package]
name = "bluetooth-rs"
version = "0.1.0"
authors = ["Ibiyemi Abiodun <ibiyemi@intulon.com>"]
edition = "2018"

[dependencies]
libc = "0.2.48"
failure = "0.1.5"
errno = "0.2.4"
epoll = "4.0.1"
num-traits = "0.2"
num-derive = "0.2"
bitflags = "1.0.4"

[[bin]]
name = "bin"
path = "src/main.rs"
doc = false